// Global site data. Imported anywhere with `import { SITE_TITLE } from '../consts'`.

export const SITE_TITLE = 'Ridge Point';
export const SITE_TAGLINE = 'GPU inference performance, from the arithmetic up';
export const SITE_DESCRIPTION =
	'Notes on GPU inference performance: profiling, kernels, and the arithmetic that decides which side of the roofline you land on. Plus a 365-day AI infrastructure self-study course, written in Chinese.';

export const AUTHOR = 'Min Liu';

export const SOCIALS = {
	github: 'https://github.com/lm742611149',
};

// Social-preview image used when a page has no image of its own.
// Generated by `npm run og` (scripts/gen-og.mjs) into public/og/.
export const DEFAULT_OG_IMAGE = '/og/default.png';
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

// Course series identifier, shared by the content schema, the /course page and the OG generator.
export const COURSE_SERIES = 'aiinfra-365';
export const COURSE_TITLE = '365 天 AI Infra 自学课程';

/** BCP 47 tag for <html lang> and og:locale, from the content schema's short `lang`. */
export const LANG_TAG: Record<'en' | 'zh', string> = { en: 'en', zh: 'zh-CN' };
export const OG_LOCALE: Record<'en' | 'zh', string> = { en: 'en_US', zh: 'zh_CN' };
